### ISSUE TITLE
Next steps when the APK is aligned and signed?

### ISSUE THREAD

**Issue by Andres6936** [sterrasec/apkutil#13]
The instructions should further specify the steps to follow once the APK has been aligned and signed.

**Comment by tkmru** [comment]
@Andres6936 Sorry for the late reply, after running `apkutil all` a re-signed APK is generated. `adb install` will successfully install the re-signed APK.

```
$ adb install sample.patched.apk
```

**Comment by Andres6936** [comment]
Thanks, Sadly, I discovered that the APK that was re-signed is part of an Apk Bundle.
