### ISSUE TITLE
Bundle support

### ISSUE THREAD

**Issue by carstenhag** [sterrasec/apkutil#4]
Hello there, saw the post on reddit. Are bundles supported as well? Did not read it on the readme, so I'm not sure whether it's supported already or not :)

 Would be interesting to have, as we usually build bundles, and I would like to analyze our own bundles.

**Comment by tkmru** [comment]
apkutil depends on apktool. Since apktool does [not seem to support bundles at the moment](https://github.com/iBotPeaches/Apktool/issues/2065), apkutil does not support bundles either.

I think it would be interesting if it could be supported.

**Comment by n0kovo** [comment]
Would love this feature as well
