### ISSUE TITLE
Windows対応

### ISSUE THREAD

**Issue by DoranekoSystems** [sterrasec/apkutil#8]
素晴らしいプロジェクトを作成していただき誠に有難うございます。
Windowsで上手く動作しなかったので、幾つかの修正を行い対応させました。

https://github.com/DoranekoSystems/apkutil

Pull Requestを送らせて頂きたいのですが、python2にも対応させる必要がありますか?

**Comment by tkmru** [comment]
ありがとうございます。Python2には対応しなくて大丈夫です。

**Comment by DoranekoSystems** [comment]
承知しました。
送らせていただいたPRについて、MacとWindowsで動作確認はしております。
